"""Catalog seed data — real phone models with specs and image URLs."""

from datetime import date
from decimal import Decimal

BRANDS = [
    {
        "name": "Apple",
        "slug": "apple",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    },
    {
        "name": "Samsung",
        "slug": "samsung",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg",
    },
    {
        "name": "Google",
        "slug": "google",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    },
    {
        "name": "Xiaomi",
        "slug": "xiaomi",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Xiaomi_logo_%282021-%29.svg",
    },
    {
        "name": "Nothing",
        "slug": "nothing",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Nothing_Technology_logo.svg",
    },
    {
        "name": "OnePlus",
        "slug": "oneplus",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/0/05/OnePlus_logo.svg",
    },
    {
        "name": "Motorola",
        "slug": "motorola",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Motorola_logo.svg",
    },
]

CATEGORIES = [
    {"name": "Flagship", "slug": "flagship", "description": "Premium top-tier devices"},
    {"name": "Mid-Range", "slug": "mid-range", "description": "Balanced performance and value"},
    {"name": "Budget", "slug": "budget", "description": "Affordable everyday phones"},
]

PHONES = [
    {
        "brand": "apple",
        "category": "flagship",
        "name": "iPhone 16 Pro Max",
        "slug": "iphone-16-pro-max",
        "model_year": 2024,
        "price": Decimal("1199"),
        "original_price": Decimal("1199"),
        "discount_percent": None,
        "description": (
            "Apple's largest Pro model with A18 Pro chip, 5x telephoto zoom, "
            "titanium design, and all-day battery in a 6.9-inch display."
        ),
        "cpu": "Apple A18 Pro",
        "gpu": "6-core GPU",
        "ram_gb": 8,
        "storage_gb": 256,
        "battery_mah": 4685,
        "charging_watts": 27,
        "camera_main_mp": 48.0,
        "camera_ultra_mp": 48.0,
        "camera_tele_mp": 12.0,
        "camera_front_mp": 12.0,
        "performance_score": 96.0,
        "camera_score": 94.0,
        "battery_score": 88.0,
        "display_score": 97.0,
        "rating_avg": 4.7,
        "review_count": 284,
        "weight_grams": 227.0,
        "dimensions": "163.0 x 77.6 x 8.3 mm",
        "colors": ["Black Titanium", "White Titanium", "Natural Titanium", "Desert Titanium"],
        "release_date": date(2024, 9, 20),
        "view_count": 1240,
        "recommendation_count": 89,
        "advantages": ["Best-in-class video", "Long iOS support", "Premium build"],
        "disadvantages": ["Very expensive", "8GB RAM only", "Slow wired charging"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": False,
            "refresh_rate_hz": 120,
            "display_type": "OLED",
            "display_size_inches": 6.9,
            "display_resolution": "2868x1320",
            "ip_rating": "IP68",
            "os_version": "iOS 18",
            "sim_type": "Nano-SIM + eSIM",
            "bluetooth": "5.3",
            "wifi": "Wi-Fi 7",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg",
            "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg",
        ],
        "price_history": [
            {"price": Decimal("1199"), "original_price": None},
            {"price": Decimal("1149"), "original_price": Decimal("1199"), "discount_percent": 4.2},
        ],
    },
    {
        "brand": "apple",
        "category": "flagship",
        "name": "iPhone 16",
        "slug": "iphone-16",
        "model_year": 2024,
        "price": Decimal("799"),
        "original_price": Decimal("829"),
        "discount_percent": 3.6,
        "description": (
            "Mainstream iPhone with A18 chip, Action Button, Camera Control, "
            "and excellent efficiency in a compact 6.1-inch body."
        ),
        "cpu": "Apple A18",
        "gpu": "5-core GPU",
        "ram_gb": 8,
        "storage_gb": 128,
        "battery_mah": 3561,
        "charging_watts": 25,
        "camera_main_mp": 48.0,
        "camera_ultra_mp": 12.0,
        "camera_tele_mp": None,
        "camera_front_mp": 12.0,
        "performance_score": 90.0,
        "camera_score": 86.0,
        "battery_score": 82.0,
        "display_score": 88.0,
        "rating_avg": 4.5,
        "review_count": 412,
        "weight_grams": 170.0,
        "dimensions": "147.6 x 71.6 x 7.8 mm",
        "colors": ["Black", "White", "Pink", "Teal", "Ultramarine"],
        "release_date": date(2024, 9, 20),
        "view_count": 980,
        "recommendation_count": 156,
        "advantages": ["Great value in Apple lineup", "Compact size", "Smooth iOS"],
        "disadvantages": ["60Hz display on base model", "128GB base storage", "No telephoto"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": False,
            "has_fingerprint": False,
            "refresh_rate_hz": 60,
            "display_type": "OLED",
            "display_size_inches": 6.1,
            "display_resolution": "2556x1179",
            "ip_rating": "IP68",
            "os_version": "iOS 18",
            "sim_type": "Nano-SIM + eSIM",
            "bluetooth": "5.3",
            "wifi": "Wi-Fi 7",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg",
        ],
        "price_history": [
            {"price": Decimal("829"), "original_price": None},
            {"price": Decimal("799"), "original_price": Decimal("829"), "discount_percent": 3.6},
        ],
    },
    {
        "brand": "apple",
        "category": "mid-range",
        "name": "iPhone 13",
        "slug": "iphone-13",
        "model_year": 2021,
        "price": Decimal("599"),
        "original_price": Decimal("799"),
        "discount_percent": 25.0,
        "description": (
            "Still-popular Apple phone with A15 Bionic, excellent battery life, "
            "dual 12MP cameras, and iOS 18 support at a reduced price."
        ),
        "cpu": "Apple A15 Bionic",
        "gpu": "5-core GPU",
        "ram_gb": 4,
        "storage_gb": 128,
        "battery_mah": 3240,
        "charging_watts": 20,
        "camera_main_mp": 12.0,
        "camera_ultra_mp": 12.0,
        "camera_tele_mp": None,
        "camera_front_mp": 12.0,
        "performance_score": 78.0,
        "camera_score": 82.0,
        "battery_score": 85.0,
        "display_score": 80.0,
        "rating_avg": 4.6,
        "review_count": 1240,
        "weight_grams": 174.0,
        "dimensions": "146.7 x 71.5 x 7.7 mm",
        "colors": ["Midnight", "Starlight", "Blue", "Pink", "Red"],
        "release_date": date(2021, 9, 24),
        "view_count": 2450,
        "recommendation_count": 310,
        "advantages": ["Great battery life", "Strong A15 chip", "Now discounted"],
        "disadvantages": ["60Hz display", "4GB RAM", "Lightning port"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": False,
            "has_fingerprint": False,
            "refresh_rate_hz": 60,
            "display_type": "OLED",
            "display_size_inches": 6.1,
            "display_resolution": "2532x1170",
            "ip_rating": "IP68",
            "os_version": "iOS 18",
            "sim_type": "Nano-SIM + eSIM",
            "bluetooth": "5.0",
            "wifi": "Wi-Fi 6",
            "usb_type": "Lightning",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
        ],
        "price_history": [
            {"price": Decimal("799"), "original_price": None},
            {"price": Decimal("699"), "original_price": Decimal("799"), "discount_percent": 12.5},
            {"price": Decimal("599"), "original_price": Decimal("799"), "discount_percent": 25.0},
        ],
    },
    {
        "brand": "samsung",
        "category": "flagship",
        "name": "Samsung Galaxy S25 Ultra",
        "slug": "galaxy-s25-ultra",
        "model_year": 2025,
        "price": Decimal("1299"),
        "original_price": None,
        "discount_percent": None,
        "description": (
            "Samsung's ultimate flagship with S Pen, 200MP camera, Snapdragon 8 Elite, "
            "and a bright 6.9-inch Dynamic AMOLED 2X display."
        ),
        "cpu": "Snapdragon 8 Elite",
        "gpu": "Adreno 830",
        "ram_gb": 12,
        "storage_gb": 256,
        "battery_mah": 5000,
        "charging_watts": 45,
        "camera_main_mp": 200.0,
        "camera_ultra_mp": 50.0,
        "camera_tele_mp": 50.0,
        "camera_front_mp": 12.0,
        "performance_score": 97.0,
        "camera_score": 96.0,
        "battery_score": 89.0,
        "display_score": 98.0,
        "rating_avg": 4.6,
        "review_count": 198,
        "weight_grams": 218.0,
        "dimensions": "162.8 x 77.6 x 8.2 mm",
        "colors": [
            "Titanium Black",
            "Titanium Gray",
            "Titanium Silverblue",
            "Titanium Whitesilver",
        ],
        "release_date": date(2025, 2, 7),
        "view_count": 1560,
        "recommendation_count": 112,
        "advantages": ["S Pen built-in", "Versatile 200MP camera", "Bright display"],
        "disadvantages": ["Very expensive", "Large and heavy", "One UI bloatware"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 120,
            "display_type": "AMOLED",
            "display_size_inches": 6.9,
            "display_resolution": "3120x1440",
            "ip_rating": "IP68",
            "os_version": "Android 15",
            "sim_type": "Nano-SIM + eSIM",
            "bluetooth": "5.4",
            "wifi": "Wi-Fi 7",
            "usb_type": "USB-C 3.2",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g-sm-s928.jpg",
        ],
        "price_history": [{"price": Decimal("1299"), "original_price": None}],
    },
    {
        "brand": "samsung",
        "category": "flagship",
        "name": "Samsung Galaxy Z Flip 6",
        "slug": "galaxy-z-flip-6",
        "model_year": 2024,
        "price": Decimal("999"),
        "original_price": Decimal("1099"),
        "discount_percent": 9.1,
        "description": (
            "Foldable flip phone with large cover screen, improved durability, "
            "and flagship Snapdragon 8 Gen 3 performance in a pocketable form."
        ),
        "cpu": "Snapdragon 8 Gen 3",
        "gpu": "Adreno 750",
        "ram_gb": 12,
        "storage_gb": 256,
        "battery_mah": 4000,
        "charging_watts": 25,
        "camera_main_mp": 50.0,
        "camera_ultra_mp": 12.0,
        "camera_tele_mp": None,
        "camera_front_mp": 10.0,
        "performance_score": 91.0,
        "camera_score": 84.0,
        "battery_score": 74.0,
        "display_score": 92.0,
        "rating_avg": 4.4,
        "review_count": 167,
        "weight_grams": 187.0,
        "dimensions": "165.1 x 71.9 x 6.9 mm (unfolded)",
        "colors": ["Blue", "Silver Shadow", "Mint", "Yellow"],
        "release_date": date(2024, 7, 24),
        "view_count": 890,
        "recommendation_count": 67,
        "advantages": ["Unique foldable design", "Compact when folded", "Fun cover screen"],
        "disadvantages": ["Smaller battery", "Crease visible", "Premium price"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 120,
            "display_type": "AMOLED",
            "display_size_inches": 6.7,
            "display_resolution": "2640x1080",
            "ip_rating": "IP48",
            "os_version": "Android 14",
            "sim_type": "Nano-SIM + eSIM",
            "bluetooth": "5.3",
            "wifi": "Wi-Fi 6E",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip6.jpg",
        ],
        "price_history": [
            {"price": Decimal("1099"), "original_price": None},
            {"price": Decimal("999"), "original_price": Decimal("1099"), "discount_percent": 9.1},
        ],
    },
    {
        "brand": "google",
        "category": "flagship",
        "name": "Google Pixel 9 Pro",
        "slug": "pixel-9-pro",
        "model_year": 2024,
        "price": Decimal("999"),
        "original_price": None,
        "discount_percent": None,
        "description": (
            "Google's AI-first flagship with Tensor G4, exceptional computational photography, "
            "7 years of updates, and clean Android experience."
        ),
        "cpu": "Google Tensor G4",
        "gpu": "Mali-G715",
        "ram_gb": 16,
        "storage_gb": 128,
        "battery_mah": 4700,
        "charging_watts": 30,
        "camera_main_mp": 50.0,
        "camera_ultra_mp": 48.0,
        "camera_tele_mp": 48.0,
        "camera_front_mp": 42.0,
        "performance_score": 83.0,
        "camera_score": 97.0,
        "battery_score": 81.0,
        "display_score": 91.0,
        "rating_avg": 4.6,
        "review_count": 223,
        "weight_grams": 199.0,
        "dimensions": "152.8 x 72.0 x 8.5 mm",
        "colors": ["Obsidian", "Porcelain", "Hazel", "Rose Quartz"],
        "release_date": date(2024, 8, 22),
        "view_count": 1120,
        "recommendation_count": 98,
        "advantages": ["Best AI photo features", "7 years updates", "Stock Android"],
        "disadvantages": ["Tensor thermals", "Average gaming", "Slow charging"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 120,
            "display_type": "OLED",
            "display_size_inches": 6.3,
            "display_resolution": "2856x1280",
            "ip_rating": "IP68",
            "os_version": "Android 15",
            "sim_type": "Nano-SIM + eSIM",
            "bluetooth": "5.3",
            "wifi": "Wi-Fi 7",
            "usb_type": "USB-C 3.2",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-1.jpg",
        ],
        "price_history": [{"price": Decimal("999"), "original_price": None}],
    },
    {
        "brand": "google",
        "category": "budget",
        "name": "Google Pixel 8a",
        "slug": "pixel-8a",
        "model_year": 2024,
        "price": Decimal("499"),
        "original_price": Decimal("549"),
        "discount_percent": 9.1,
        "description": (
            "Affordable Pixel with flagship-class camera processing, Tensor G3, "
            "and the same long update promise at a mid-range price."
        ),
        "cpu": "Google Tensor G3",
        "gpu": "Mali-G715",
        "ram_gb": 8,
        "storage_gb": 128,
        "battery_mah": 4492,
        "charging_watts": 18,
        "camera_main_mp": 64.0,
        "camera_ultra_mp": 13.0,
        "camera_tele_mp": None,
        "camera_front_mp": 13.0,
        "performance_score": 76.0,
        "camera_score": 89.0,
        "battery_score": 77.0,
        "display_score": 81.0,
        "rating_avg": 4.5,
        "review_count": 356,
        "weight_grams": 188.0,
        "dimensions": "152.1 x 72.7 x 8.9 mm",
        "colors": ["Obsidian", "Porcelain", "Bay", "Aloe"],
        "release_date": date(2024, 5, 14),
        "view_count": 1340,
        "recommendation_count": 201,
        "advantages": ["Flagship camera at mid price", "Clean Android", "Long updates"],
        "disadvantages": ["60Hz display", "Average battery", "Slow charging"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": False,
            "has_fingerprint": True,
            "refresh_rate_hz": 60,
            "display_type": "OLED",
            "display_size_inches": 6.1,
            "display_resolution": "2400x1080",
            "ip_rating": "IP67",
            "os_version": "Android 14",
            "sim_type": "Nano-SIM + eSIM",
            "bluetooth": "5.3",
            "wifi": "Wi-Fi 6E",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8a.jpg",
        ],
        "price_history": [
            {"price": Decimal("549"), "original_price": None},
            {"price": Decimal("499"), "original_price": Decimal("549"), "discount_percent": 9.1},
        ],
    },
    {
        "brand": "xiaomi",
        "category": "flagship",
        "name": "Xiaomi 14 Ultra",
        "slug": "xiaomi-14-ultra",
        "model_year": 2024,
        "price": Decimal("1299"),
        "original_price": None,
        "discount_percent": None,
        "description": (
            "Camera-focused flagship co-engineered with Leica, Snapdragon 8 Gen 3, "
            "1-inch main sensor, and 90W wired + 80W wireless charging."
        ),
        "cpu": "Snapdragon 8 Gen 3",
        "gpu": "Adreno 750",
        "ram_gb": 16,
        "storage_gb": 512,
        "battery_mah": 5300,
        "charging_watts": 90,
        "camera_main_mp": 50.0,
        "camera_ultra_mp": 50.0,
        "camera_tele_mp": 50.0,
        "camera_front_mp": 32.0,
        "performance_score": 95.0,
        "camera_score": 98.0,
        "battery_score": 91.0,
        "display_score": 94.0,
        "rating_avg": 4.5,
        "review_count": 142,
        "weight_grams": 224.0,
        "dimensions": "161.4 x 75.3 x 9.2 mm",
        "colors": ["Black", "White"],
        "release_date": date(2024, 2, 25),
        "view_count": 670,
        "recommendation_count": 54,
        "advantages": ["Leica cameras", "Insane fast charging", "Top performance"],
        "disadvantages": ["Heavy", "Limited global availability", "HyperOS learning curve"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": False,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 120,
            "display_type": "AMOLED",
            "display_size_inches": 6.73,
            "display_resolution": "3200x1440",
            "ip_rating": "IP68",
            "os_version": "Android 14",
            "sim_type": "Dual Nano-SIM",
            "bluetooth": "5.4",
            "wifi": "Wi-Fi 7",
            "usb_type": "USB-C 3.2",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-13-ultra.jpg",
        ],
        "price_history": [{"price": Decimal("1299"), "original_price": None}],
    },
    {
        "brand": "xiaomi",
        "category": "mid-range",
        "name": "Xiaomi 14T Pro",
        "slug": "xiaomi-14t-pro",
        "model_year": 2024,
        "price": Decimal("649"),
        "original_price": Decimal("699"),
        "discount_percent": 7.2,
        "description": (
            "Performance flagship killer with MediaTek Dimensity 9300+, "
            "144Hz AMOLED, and 120W HyperCharge at a competitive price."
        ),
        "cpu": "MediaTek Dimensity 9300+",
        "gpu": "Mali-G720",
        "ram_gb": 12,
        "storage_gb": 256,
        "battery_mah": 5000,
        "charging_watts": 120,
        "camera_main_mp": 50.0,
        "camera_ultra_mp": 50.0,
        "camera_tele_mp": None,
        "camera_front_mp": 32.0,
        "performance_score": 89.0,
        "camera_score": 86.0,
        "battery_score": 92.0,
        "display_score": 89.0,
        "rating_avg": 4.4,
        "review_count": 189,
        "weight_grams": 209.0,
        "dimensions": "160.4 x 75.1 x 8.6 mm",
        "colors": ["Titan Black", "Titan Gray", "Titan Blue"],
        "release_date": date(2024, 9, 26),
        "view_count": 780,
        "recommendation_count": 93,
        "advantages": ["120W charging", "Strong performance", "144Hz display"],
        "disadvantages": ["No wireless charging", "MIUI ads", "No telephoto"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": False,
            "has_esim": False,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 144,
            "display_type": "AMOLED",
            "display_size_inches": 6.67,
            "display_resolution": "2712x1220",
            "ip_rating": "IP54",
            "os_version": "Android 14",
            "sim_type": "Dual Nano-SIM",
            "bluetooth": "5.4",
            "wifi": "Wi-Fi 7",
            "usb_type": "USB-C 2.0",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14t-pro.jpg",
        ],
        "price_history": [
            {"price": Decimal("699"), "original_price": None},
            {"price": Decimal("649"), "original_price": Decimal("699"), "discount_percent": 7.2},
        ],
    },
    {
        "brand": "xiaomi",
        "category": "budget",
        "name": "Redmi Note 14 Pro",
        "slug": "redmi-note-14-pro",
        "model_year": 2025,
        "price": Decimal("299"),
        "original_price": None,
        "discount_percent": None,
        "description": (
            "Budget champion with 200MP main camera, 5110mAh battery, "
            "120Hz AMOLED, and IP54 rating at an unbeatable price."
        ),
        "cpu": "MediaTek Dimensity 7300",
        "gpu": "Mali-G615",
        "ram_gb": 8,
        "storage_gb": 256,
        "battery_mah": 5110,
        "charging_watts": 45,
        "camera_main_mp": 200.0,
        "camera_ultra_mp": 8.0,
        "camera_tele_mp": None,
        "camera_front_mp": 20.0,
        "performance_score": 69.0,
        "camera_score": 74.0,
        "battery_score": 93.0,
        "display_score": 79.0,
        "rating_avg": 4.3,
        "review_count": 521,
        "weight_grams": 180.0,
        "dimensions": "162.4 x 74.9 x 8.2 mm",
        "colors": ["Midnight Black", "Aurora Purple", "Coral Green"],
        "release_date": date(2025, 1, 10),
        "view_count": 2100,
        "recommendation_count": 287,
        "advantages": ["Incredible value", "Huge battery", "200MP sensor"],
        "disadvantages": ["Plastic frame", "Ads in UI", "Average processor"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": False,
            "has_esim": False,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 120,
            "display_type": "AMOLED",
            "display_size_inches": 6.67,
            "display_resolution": "2712x1220",
            "ip_rating": "IP54",
            "os_version": "Android 14",
            "sim_type": "Dual Nano-SIM",
            "bluetooth": "5.3",
            "wifi": "Wi-Fi 6",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-pro-5g.jpg",
        ],
        "price_history": [{"price": Decimal("299"), "original_price": None}],
    },
    {
        "brand": "nothing",
        "category": "mid-range",
        "name": "Nothing Phone (2a)",
        "slug": "nothing-phone-2a",
        "model_year": 2024,
        "price": Decimal("349"),
        "original_price": Decimal("399"),
        "discount_percent": 12.5,
        "description": (
            "Distinctive Glyph design with clean Nothing OS, Snapdragon 7s Gen 2, "
            "and solid everyday performance for design-conscious buyers."
        ),
        "cpu": "Snapdragon 7s Gen 2",
        "gpu": "Adreno 710",
        "ram_gb": 8,
        "storage_gb": 128,
        "battery_mah": 5000,
        "charging_watts": 45,
        "camera_main_mp": 50.0,
        "camera_ultra_mp": 50.0,
        "camera_tele_mp": None,
        "camera_front_mp": 32.0,
        "performance_score": 72.0,
        "camera_score": 78.0,
        "battery_score": 87.0,
        "display_score": 84.0,
        "rating_avg": 4.2,
        "review_count": 278,
        "weight_grams": 190.0,
        "dimensions": "162.1 x 76.3 x 8.6 mm",
        "colors": ["Black", "White", "Milk"],
        "release_date": date(2024, 3, 12),
        "view_count": 920,
        "recommendation_count": 118,
        "advantages": ["Unique Glyph design", "Clean Nothing OS", "Good battery"],
        "disadvantages": ["Mid-range chip", "Average camera", "No wireless charging"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": False,
            "has_esim": False,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 120,
            "display_type": "AMOLED",
            "display_size_inches": 6.7,
            "display_resolution": "2412x1080",
            "ip_rating": "IP54",
            "os_version": "Android 14",
            "sim_type": "Dual Nano-SIM",
            "bluetooth": "5.2",
            "wifi": "Wi-Fi 6",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg",
        ],
        "price_history": [
            {"price": Decimal("399"), "original_price": None},
            {"price": Decimal("349"), "original_price": Decimal("399"), "discount_percent": 12.5},
        ],
    },
    {
        "brand": "oneplus",
        "category": "flagship",
        "name": "OnePlus 13",
        "slug": "oneplus-13",
        "model_year": 2025,
        "price": Decimal("899"),
        "original_price": None,
        "discount_percent": None,
        "description": (
            "Speed-focused flagship with Snapdragon 8 Elite, 6000mAh battery, "
            "100W SUPERVOOC charging, and Hasselblad-tuned cameras."
        ),
        "cpu": "Snapdragon 8 Elite",
        "gpu": "Adreno 830",
        "ram_gb": 12,
        "storage_gb": 256,
        "battery_mah": 6000,
        "charging_watts": 100,
        "camera_main_mp": 50.0,
        "camera_ultra_mp": 50.0,
        "camera_tele_mp": 50.0,
        "camera_front_mp": 32.0,
        "performance_score": 96.0,
        "camera_score": 90.0,
        "battery_score": 95.0,
        "display_score": 93.0,
        "rating_avg": 4.5,
        "review_count": 156,
        "weight_grams": 210.0,
        "dimensions": "162.9 x 76.5 x 8.5 mm",
        "colors": ["Black Eclipse", "Arctic Dawn", "Emerald Flow"],
        "release_date": date(2025, 1, 7),
        "view_count": 740,
        "recommendation_count": 61,
        "advantages": ["100W charging", "Huge 6000mAh battery", "Smooth OxygenOS"],
        "disadvantages": ["No microSD", "Large size", "Camera not class-leading"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 120,
            "display_type": "AMOLED",
            "display_size_inches": 6.82,
            "display_resolution": "3168x1440",
            "ip_rating": "IP68",
            "os_version": "Android 15",
            "sim_type": "Dual Nano-SIM",
            "bluetooth": "5.4",
            "wifi": "Wi-Fi 7",
            "usb_type": "USB-C 3.2",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13.jpg",
        ],
        "price_history": [{"price": Decimal("899"), "original_price": None}],
    },
    {
        "brand": "samsung",
        "category": "mid-range",
        "name": "Samsung Galaxy A55",
        "slug": "galaxy-a55",
        "model_year": 2024,
        "price": Decimal("449"),
        "original_price": Decimal("479"),
        "discount_percent": 6.3,
        "description": (
            "Reliable mid-ranger with Exynos 1480, IP67 water resistance, "
            "5000mAh battery, and 4 years of Android updates."
        ),
        "cpu": "Exynos 1480",
        "gpu": "Xclipse 530",
        "ram_gb": 8,
        "storage_gb": 128,
        "battery_mah": 5000,
        "charging_watts": 25,
        "camera_main_mp": 50.0,
        "camera_ultra_mp": 12.0,
        "camera_tele_mp": None,
        "camera_front_mp": 32.0,
        "performance_score": 73.0,
        "camera_score": 76.0,
        "battery_score": 88.0,
        "display_score": 83.0,
        "rating_avg": 4.3,
        "review_count": 445,
        "weight_grams": 213.0,
        "dimensions": "161.1 x 77.4 x 8.2 mm",
        "colors": ["Awesome Iceblue", "Awesome Lilac", "Awesome Lemon", "Awesome Navy"],
        "release_date": date(2024, 3, 15),
        "view_count": 1180,
        "recommendation_count": 134,
        "advantages": ["IP67 rating", "Great battery", "Samsung updates"],
        "disadvantages": ["25W charging", "Exynos performance", "No telephoto"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": False,
            "has_esim": False,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 120,
            "display_type": "AMOLED",
            "display_size_inches": 6.6,
            "display_resolution": "2340x1080",
            "ip_rating": "IP67",
            "os_version": "Android 14",
            "sim_type": "Dual Nano-SIM",
            "bluetooth": "5.3",
            "wifi": "Wi-Fi 6",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg",
        ],
        "price_history": [
            {"price": Decimal("479"), "original_price": None},
            {"price": Decimal("449"), "original_price": Decimal("479"), "discount_percent": 6.3},
        ],
    },
    {
        "brand": "motorola",
        "category": "mid-range",
        "name": "Motorola Edge 50 Pro",
        "slug": "motorola-edge-50-pro",
        "model_year": 2024,
        "price": Decimal("499"),
        "original_price": None,
        "discount_percent": None,
        "description": (
            "Slim mid-range with Snapdragon 7 Gen 3, 50MP triple camera, "
            "125W turbo charging, and near-stock Android experience."
        ),
        "cpu": "Snapdragon 7 Gen 3",
        "gpu": "Adreno 720",
        "ram_gb": 12,
        "storage_gb": 256,
        "battery_mah": 4500,
        "charging_watts": 125,
        "camera_main_mp": 50.0,
        "camera_ultra_mp": 13.0,
        "camera_tele_mp": None,
        "camera_front_mp": 50.0,
        "performance_score": 78.0,
        "camera_score": 80.0,
        "battery_score": 79.0,
        "display_score": 87.0,
        "rating_avg": 4.2,
        "review_count": 198,
        "weight_grams": 186.0,
        "dimensions": "161.2 x 72.4 x 7.6 mm",
        "colors": ["Luxe Lavender", "Black Beauty", "Moonlight Pearl"],
        "release_date": date(2024, 4, 16),
        "view_count": 560,
        "recommendation_count": 72,
        "advantages": ["125W charging", "Very slim", "Clean Android"],
        "disadvantages": ["Smaller battery", "Motorola updates", "Average ultrawide"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": False,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 144,
            "display_type": "AMOLED",
            "display_size_inches": 6.7,
            "display_resolution": "2712x1220",
            "ip_rating": "IP68",
            "os_version": "Android 14",
            "sim_type": "Dual Nano-SIM",
            "bluetooth": "5.2",
            "wifi": "Wi-Fi 6E",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-pro.jpg",
        ],
        "price_history": [{"price": Decimal("499"), "original_price": None}],
    },
    {
        "brand": "apple",
        "category": "mid-range",
        "name": "iPhone 15",
        "slug": "iphone-15",
        "model_year": 2023,
        "price": Decimal("699"),
        "original_price": Decimal("799"),
        "discount_percent": 12.5,
        "description": (
            "Previous-gen iPhone still highly relevant: A16 Bionic, Dynamic Island, "
            "48MP main camera, and USB-C at a reduced price."
        ),
        "cpu": "Apple A16 Bionic",
        "gpu": "5-core GPU",
        "ram_gb": 6,
        "storage_gb": 128,
        "battery_mah": 3349,
        "charging_watts": 20,
        "camera_main_mp": 48.0,
        "camera_ultra_mp": 12.0,
        "camera_tele_mp": None,
        "camera_front_mp": 12.0,
        "performance_score": 85.0,
        "camera_score": 84.0,
        "battery_score": 78.0,
        "display_score": 86.0,
        "rating_avg": 4.6,
        "review_count": 892,
        "weight_grams": 171.0,
        "dimensions": "147.6 x 71.6 x 7.8 mm",
        "colors": ["Black", "Blue", "Green", "Yellow", "Pink"],
        "release_date": date(2023, 9, 22),
        "view_count": 1890,
        "recommendation_count": 245,
        "advantages": ["Now discounted", "iOS ecosystem", "Great cameras"],
        "disadvantages": ["60Hz display", "6GB RAM", "20W charging"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": True,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": False,
            "has_fingerprint": False,
            "refresh_rate_hz": 60,
            "display_type": "OLED",
            "display_size_inches": 6.1,
            "display_resolution": "2556x1179",
            "ip_rating": "IP68",
            "os_version": "iOS 18",
            "sim_type": "Nano-SIM + eSIM",
            "bluetooth": "5.3",
            "wifi": "Wi-Fi 6",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg",
        ],
        "price_history": [
            {"price": Decimal("799"), "original_price": None},
            {"price": Decimal("749"), "original_price": Decimal("799"), "discount_percent": 6.3},
            {"price": Decimal("699"), "original_price": Decimal("799"), "discount_percent": 12.5},
        ],
    },
    {
        "brand": "google",
        "category": "mid-range",
        "name": "Google Pixel 9a",
        "slug": "pixel-9a",
        "model_year": 2025,
        "price": Decimal("499"),
        "original_price": None,
        "discount_percent": None,
        "description": (
            "Latest affordable Pixel with Tensor G4, flagship AI features, "
            "solid battery life, and the best software support in its class."
        ),
        "cpu": "Google Tensor G4",
        "gpu": "Mali-G715",
        "ram_gb": 8,
        "storage_gb": 128,
        "battery_mah": 5100,
        "charging_watts": 23,
        "camera_main_mp": 48.0,
        "camera_ultra_mp": 13.0,
        "camera_tele_mp": None,
        "camera_front_mp": 13.0,
        "performance_score": 80.0,
        "camera_score": 91.0,
        "battery_score": 86.0,
        "display_score": 84.0,
        "rating_avg": 4.4,
        "review_count": 134,
        "weight_grams": 186.0,
        "dimensions": "154.7 x 73.3 x 8.9 mm",
        "colors": ["Obsidian", "Porcelain", "Iris", "Peony"],
        "release_date": date(2025, 3, 19),
        "view_count": 620,
        "recommendation_count": 88,
        "advantages": ["Tensor G4 at mid price", "7 years updates", "Great AI tools"],
        "disadvantages": ["Plastic back", "Slow charging", "No wireless charging"],
        "features": {
            "has_5g": True,
            "has_nfc": True,
            "has_wireless_charging": False,
            "has_esim": True,
            "has_amoled": True,
            "has_high_refresh": True,
            "has_fingerprint": True,
            "refresh_rate_hz": 120,
            "display_type": "OLED",
            "display_size_inches": 6.3,
            "display_resolution": "2424x1080",
            "ip_rating": "IP68",
            "os_version": "Android 15",
            "sim_type": "Nano-SIM + eSIM",
            "bluetooth": "5.3",
            "wifi": "Wi-Fi 6E",
            "usb_type": "USB-C",
            "stereo_speakers": True,
        },
        "images": [
            "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9a.jpg",
        ],
        "price_history": [{"price": Decimal("499"), "original_price": None}],
    },
]
